config/routes.rb
Rails.application.routes.draw do
  resources :experiments
  resources :comments
  root 'home#index'

  get 'experiments/react' => 'experiements#react'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  ######################################################################
  # BEGIN EXPERIMENT PAGES
  ######################################################################
  def react

  end

  ######################################################################
  # END EXPERIMENT PAGES
  ######################################################################


  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
    if (!@experiment.link.empty?)
      # TODO: Check if the page actually exists
      render @experiment.link
    end
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find_by_link(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:name, :description, :link)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@experiments = Experiment.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/_list.html.erb
<div class="experiments">
	<h1>Experiments</h1>
	<% @experiments.each do |e| %>
		<a href="/experiments/<%= e.link %>" class="exp-link">
			<div class="experiment">
				<div class="exp-name">
					<h1><%= e.name %></h1>
				</div>
				<div class="exp-description">
					<p><%= e.description %></p>
				</div>
			</div>
		</a>
		<%= link_to 'Edit', edit_experiment_path(e) %>
	<% end %>
	<%= link_to 'New Experiment', new_experiment_path %>
</div>

app/views/experiments/css_outline.html.erb
<article>
	<h1>This page is an article. This text is an h1 tag</h1>
	<h2>This is an h2 tag</h2>
	<h3>This is an h3 tag</h3>
	<h4>This is an h4 tag</h4>
	<h5>This is an h5 tag</h5>
	<h6>This is an h6 tag</h6>
	<div>This is a div</div>
	<p>This is a paragraph</p>
</article>

app/views/experiments/edit.html.erb
<h1>Editing Experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Experiments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.name %></td>
        <td><%= experiment.description %></td>
        <td><%= experiment.link %></td>
        <td><%= link_to 'Show', experiment %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
        <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/material_design.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'material_design' %>
<% end %>

<div class="page-header">
	<h1>Material Design</h1>
</div>
<div class="page-body">
	<p>This page aims to practice and explain some of the principles behind Google's "Material Design". In Material Design, components existing on a webpage are thought to be pieces of material that represent a stronger analog to real life interactions.</p>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>
<div class="material">
	<div class="material-header">
		<h1>This is a piece of material</h1>
	</div>
	<div class="material-body">
		<p>Note that this material has it's own shape and size</p>
	</div>
</div>

app/views/experiments/new.html.erb
<h1>New Experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/react.html.erb
<%= react_component 'React', {data: @experiment} %>

This page is very broken

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @experiment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experiment.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @experiment.link %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>

app/views/home/index.html.erb
<%= render 'experiments/list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="body">
	<%= render 'shared/header' %>
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'shared/footer' %>
</div>

</body>
</html>

app/views/shared/_footer.html.erb
<footer class="main-footer">
	<div class="col-6">
		<h1>About this site</h1>
		<p>This site is powered by Ruby on rails. This page doesn't uses any CSS frameworks, but it aims to mimic Bootstrap's 12 column page organization. The CSS is all custom and uses SCSS as its preprocessor.</p>
	</div>
	<div class="col-6" id="about-me">
		<h1>About me</h1>
		<ul>
			<li>Education: BS in CS from UCSB</li>
			<li>Employment: Software Engineer</li>
		</ul>
	</div>
</footer>

app/views/shared/_header.html.erb
<header class="main-header">
  <a class="logo" href="/">Sandbox</a>
</header>